DELETE FROM user;
DELETE FROM annotation_result; 
DELETE FROM summsummaries_pair;
DELETE FROM summary_status;
DELETE FROM summary_group;
DELETE FROM summary;
DELETE FROM evaluation_result;
DELETE FROM evaluation_project;
DELETE FROM doc_status;
DELETE FROM document;
DELETE FROM alembic_version;
DELETE FROM annotation_project;
DELETE FROM dataset
